# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@alcalzone/ansi-tokenize@0.2.5" = fetchurl {
    url = "https://registry.npmjs.org/@alcalzone/ansi-tokenize/-/ansi-tokenize-0.2.5.tgz";
    hash = "sha512-3NX/MpTdroi0aKz134A6RC2Gb2iXVECN4QaAXnvCIxxIm3C3AVB1mkUe8NaaiyvOpDfsrqWhYtj+Q6a62RrTsw==";
  };
  "@types/bun@1.3.14" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.3.14.tgz";
    hash = "sha512-h1hFqFVcvAvD9j9K7ZW7vd82aSA+rTdznZa+5bwvCwqSB1jmmfLcbIWhOLx1/+boy/xmjgCs/OMUL8hRJSmnPw==";
  };
  "@types/node@25.9.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-25.9.1.tgz";
    hash = "sha512-xfrlY7UD5rMJk3ZVJP8BNzS28J36YJg+xp+LPXV1TdWxr8uMH5A860QNxYDGQe/ylDSgjxE52Q9VnO7p75tJxg==";
  };
  "@types/proper-lockfile@4.1.4" = fetchurl {
    url = "https://registry.npmjs.org/@types/proper-lockfile/-/proper-lockfile-4.1.4.tgz";
    hash = "sha512-uo2ABllncSqg9F1D4nugVl9v93RmjxF6LJzQLMLDdPaXCUIDPeOJ21Gbqi43xNKzBi/WQ0Q0dICqufzQbMjipQ==";
  };
  "@types/react@19.2.16" = fetchurl {
    url = "https://registry.npmjs.org/@types/react/-/react-19.2.16.tgz";
    hash = "sha512-esJiCAnl0kfpNdE69f3So4WJUXy95dLZydX0KwK46riIHDzHM7O9Vtf9xCHW0PXIqvgqNrswl522kA/5yx+F4w==";
  };
  "@types/retry@0.12.5" = fetchurl {
    url = "https://registry.npmjs.org/@types/retry/-/retry-0.12.5.tgz";
    hash = "sha512-3xSjTp3v03X/lSQLkczaN9UIEwJMoMCA1+Nb5HfbJEQWogdeQIyVtTvxPXDQjZ5zws8rFQfVfRdz03ARihPJgw==";
  };
  "ansi-escapes@7.3.0" = fetchurl {
    url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-7.3.0.tgz";
    hash = "sha512-BvU8nYgGQBxcmMuEeUEmNTvrMVjJNSH7RgW24vXexN4Ven6qCvy4TntnvlnwnMLTVlcRQQdbRY8NKnaIoeWDNg==";
  };
  "ansi-regex@6.2.2" = fetchurl {
    url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.2.2.tgz";
    hash = "sha512-Bq3SmSpyFHaWjPk8If9yc6svM8c56dB5BAtW4Qbw5jHTwwXXcTLoRMkpDJp6VL0XzlWaCHTXrkFURMYmD0sLqg==";
  };
  "ansi-styles@6.2.3" = fetchurl {
    url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.3.tgz";
    hash = "sha512-4Dj6M28JB+oAH8kFkTLUo+a2jwOFkuqb3yucU0CANcRRUbxS0cP0nZYCGjcc3BNXwRIsUVmDGgzawme7zvJHvg==";
  };
  "auto-bind@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/auto-bind/-/auto-bind-5.0.1.tgz";
    hash = "sha512-ooviqdwwgfIfNmDwo94wlshcdzfO64XV0Cg6oDsDYBJfITDz1EngD2z7DkbvCWn+XIMsIqW27sEVF6qcpJrRcg==";
  };
  "bun-types@1.3.14" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.14.tgz";
    hash = "sha512-4N0ig0fEomHt5R0KCFWjovxow98rIoRwKolrYdCcknNwMekCXRnWEUvgu5soYV8QXtVsrUD8B95MBOZGPvr6KQ==";
  };
  "chalk@5.6.2" = fetchurl {
    url = "https://registry.npmjs.org/chalk/-/chalk-5.6.2.tgz";
    hash = "sha512-7NzBL0rN6fMUW+f7A6Io4h40qQlG+xGmtMxfbnH/K7TAtt8JQWVQK+6g0UXKMeVJoyV5EkkNsErQ8pVD3bLHbA==";
  };
  "cli-boxes@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/cli-boxes/-/cli-boxes-3.0.0.tgz";
    hash = "sha512-/lzGpEWL/8PfI0BmBOPRwp0c/wFNX1RdUML3jK/RcSBA9T8mZDdQpqYBKtCFTOfQbwPqWEOpjqW+Fnayc0969g==";
  };
  "cli-cursor@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-4.0.0.tgz";
    hash = "sha512-VGtlMu3x/4DOtIUwEkRezxUZ2lBacNJCHash0N0WeZDBS+7Ux1dm3XWAgWYxLJFMMdOeXMHXorshEFhbMSGelg==";
  };
  "cli-truncate@5.2.0" = fetchurl {
    url = "https://registry.npmjs.org/cli-truncate/-/cli-truncate-5.2.0.tgz";
    hash = "sha512-xRwvIOMGrfOAnM1JYtqQImuaNtDEv9v6oIYAs4LIHwTiKee8uwvIi363igssOC0O5U04i4AlENs79LQLu9tEMw==";
  };
  "code-excerpt@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/code-excerpt/-/code-excerpt-4.0.0.tgz";
    hash = "sha512-xxodCmBen3iy2i0WtAK8FlFNrRzjUqjRsMfho58xT/wvZU1YTM3fCnRjcy1gJPMepaRlgm/0e6w8SpWHpn3/cA==";
  };
  "convert-to-spaces@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/convert-to-spaces/-/convert-to-spaces-2.0.1.tgz";
    hash = "sha512-rcQ1bsQO9799wq24uE5AM2tAILy4gXGIK/njFWcVQkGNZ96edlpY+A7bjwvzjYvLDyzmG1MmMLZhpcsb+klNMQ==";
  };
  "csstype@3.2.3" = fetchurl {
    url = "https://registry.npmjs.org/csstype/-/csstype-3.2.3.tgz";
    hash = "sha512-z1HGKcYy2xA8AGQfwrn0PAy+PB7X/GSj3UVJW9qKyn43xWa+gl5nXmU4qqLMRzWVLFC8KusUX8T/0kCiOYpAIQ==";
  };
  "emoji-regex@10.6.0" = fetchurl {
    url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-10.6.0.tgz";
    hash = "sha512-toUI84YS5YmxW219erniWD0CIVOo46xGKColeNQRgOzDorgBi1v4D71/OFzgD9GO2UGKIv1C3Sp8DAn0+j5w7A==";
  };
  "environment@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/environment/-/environment-1.1.0.tgz";
    hash = "sha512-xUtoPkMggbz0MPyPiIWr1Kp4aeWJjDZ6SMvURhimjdZgsRuDplF5/s9hcgGhyXMhs+6vpnuoiZ2kFiu3FMnS8Q==";
  };
  "es-toolkit@1.47.0" = fetchurl {
    url = "https://registry.npmjs.org/es-toolkit/-/es-toolkit-1.47.0.tgz";
    hash = "sha512-n1GuoD0WEQZMBk5tttoZSqwgyLx01oqa5XsBmCHwPyNe1S9jPBEmtR2pSgp2kJuWE3ciFZ6yRHmY4pM4C3OOkw==";
  };
  "escape-string-regexp@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-2.0.0.tgz";
    hash = "sha512-UpzcLCXolUWcNu5HtVMHYdXJjArjsF9C0aNnquZYY4uW/Vu0miy5YoWvbV345HauVvcAUnpRuhMMcqTcGOY2+w==";
  };
  "get-east-asian-width@1.6.0" = fetchurl {
    url = "https://registry.npmjs.org/get-east-asian-width/-/get-east-asian-width-1.6.0.tgz";
    hash = "sha512-QRbvDIbx6YklUe6RxeTeleMR0yv3cYH6PsPZHcnVn7xv7zO1BHN8r0XETu8n6Ye3Q+ahtSarc3WgtNWmehIBfA==";
  };
  "graceful-fs@4.2.11" = fetchurl {
    url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
    hash = "sha512-RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
  };
  "indent-string@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/indent-string/-/indent-string-5.0.0.tgz";
    hash = "sha512-m6FAo/spmsW2Ab2fU35JTYwtOKa2yAwXSwgjSv1TJzh4Mh7mC3lzAOVLBprb72XsTrgkEIsl7YrFNAiDiRhIGg==";
  };
  "ink@6.8.0" = fetchurl {
    url = "https://registry.npmjs.org/ink/-/ink-6.8.0.tgz";
    hash = "sha512-sbl1RdLOgkO9isK42WCZlJCFN9hb++sX9dsklOvfd1YQ3bQ2AiFu12Q6tFlr0HvEUvzraJntQCCpfEoUe9DSzA==";
  };
  "is-fullwidth-code-point@5.1.0" = fetchurl {
    url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-5.1.0.tgz";
    hash = "sha512-5XHYaSyiqADb4RnZ1Bdad6cPp8Toise4TzEjcOYDHZkTCbKgiUl7WTUCpNWHuxmDt91wnsZBc9xinNzopv3JMQ==";
  };
  "is-in-ci@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-in-ci/-/is-in-ci-2.0.0.tgz";
    hash = "sha512-cFeerHriAnhrQSbpAxL37W1wcJKUUX07HyLWZCW1URJT/ra3GyUTzBgUnh24TMVfNTV2Hij2HLxkPHFZfOZy5w==";
  };
  "mimic-fn@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
    hash = "sha512-OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
  };
  "onetime@5.1.2" = fetchurl {
    url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
    hash = "sha512-kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
  };
  "patch-console@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/patch-console/-/patch-console-2.0.0.tgz";
    hash = "sha512-0YNdUceMdaQwoKce1gatDScmMo5pu/tfABfnzEqeG0gtTmd7mh/WcwgUjtAeOU7N8nFFlbQBnFK2gXW5fGvmMA==";
  };
  "proper-lockfile@4.1.2" = fetchurl {
    url = "https://registry.npmjs.org/proper-lockfile/-/proper-lockfile-4.1.2.tgz";
    hash = "sha512-TjNPblN4BwAWMXU8s9AEz4JmQxnD1NNL7bNOY/AKUzyamc379FWASUhc/K1pL2noVb+XmZKLL68cjzLsiOAMaA==";
  };
  "react-devtools-core@6.1.5" = fetchurl {
    url = "https://registry.npmjs.org/react-devtools-core/-/react-devtools-core-6.1.5.tgz";
    hash = "sha512-ePrwPfxAnB+7hgnEr8vpKxL9cmnp7F322t8oqcPshbIQQhDKgFDW4tjhF2wjVbdXF9O/nyuy3sQWd9JGpiLPvA==";
  };
  "react-reconciler@0.33.0" = fetchurl {
    url = "https://registry.npmjs.org/react-reconciler/-/react-reconciler-0.33.0.tgz";
    hash = "sha512-KetWRytFv1epdpJc3J4G75I4WrplZE5jOL7Yq0p34+OVOKF4Se7WrdIdVC45XsSSmUTlht2FM/fM1FZb1mfQeA==";
  };
  "react@19.2.7" = fetchurl {
    url = "https://registry.npmjs.org/react/-/react-19.2.7.tgz";
    hash = "sha512-HNe9WslTbXmFK8o8cmwgAeJFSBvt1bPdHCVKtaaV+WlAN36mpT4hcRpwbf3fY56ar2oIXzsBpOAiIRHAdY0OlQ==";
  };
  "restore-cursor@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-4.0.0.tgz";
    hash = "sha512-I9fPXU9geO9bHOt9pHHOhOkYerIMsmVaWB0rA2AI9ERh/+x/i7MV5HKBNrg+ljO5eoPVgCcnFuRjJ9uH6I/3eg==";
  };
  "retry@0.12.0" = fetchurl {
    url = "https://registry.npmjs.org/retry/-/retry-0.12.0.tgz";
    hash = "sha512-9LkiTwjUh6rT555DtE9rTX+BKByPfrMzEAtnlEtdEwr3Nkffwiihqe2bWADg+OQRjt9gl6ICdmB/ZFDCGAtSow==";
  };
  "scheduler@0.27.0" = fetchurl {
    url = "https://registry.npmjs.org/scheduler/-/scheduler-0.27.0.tgz";
    hash = "sha512-eNv+WrVbKu1f3vbYJT/xtiF5syA5HPIMtf9IgY/nKg0sWqzAUEvqY/xm7OcZc/qafLx/iO9FgOmeSAp4v5ti/Q==";
  };
  "shell-quote@1.8.4" = fetchurl {
    url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.8.4.tgz";
    hash = "sha512-VsC6n6vz1ihYYyZZwX7YZSF5l5x36ca17OC+a69h94YqB7X6XLwf+5MOgynYir2SLFUbl8gIYvBo8K8RoNQ6bQ==";
  };
  "signal-exit@3.0.7" = fetchurl {
    url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
    hash = "sha512-wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
  };
  "slice-ansi@8.0.0" = fetchurl {
    url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-8.0.0.tgz";
    hash = "sha512-stxByr12oeeOyY2BlviTNQlYV5xOj47GirPr4yA1hE9JCtxfQN0+tVbkxwCtYDQWhEKWFHsEK48ORg5jrouCAg==";
  };
  "stack-utils@2.0.6" = fetchurl {
    url = "https://registry.npmjs.org/stack-utils/-/stack-utils-2.0.6.tgz";
    hash = "sha512-XlkWvfIm6RmsWtNJx+uqtKLS8eqFbxUg0ZzLXqY0caEy9l7hruX8IpiDnjsLavoBgqCCR71TqWO8MaXYheJ3RQ==";
  };
  "string-width@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/string-width/-/string-width-7.2.0.tgz";
    hash = "sha512-tsaTIkKW9b4N+AEj+SVA+WhJzV7/zMhcSu78mLKWSk7cXMOSHsBKFWUs0fWwq8QyK3MgJBQRX6Gbi4kYbdvGkQ==";
  };
  "string-width@8.2.1" = fetchurl {
    url = "https://registry.npmjs.org/string-width/-/string-width-8.2.1.tgz";
    hash = "sha512-IIaP0g3iy9Cyy18w3M9YcaDudujEAVHKt3a3QJg1+sr/oX96TbaGUubG0hJyCjCBThFH+tFpcIyoUHUn1ogaLA==";
  };
  "strip-ansi@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.2.0.tgz";
    hash = "sha512-yDPMNjp4WyfYBkHnjIRLfca1i6KMyGCtsVgoKe/z1+6vukgaENdgGBZt+ZmKPc4gavvEZ5OgHfHdrazhgNyG7w==";
  };
  "tagged-tag@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/tagged-tag/-/tagged-tag-1.0.0.tgz";
    hash = "sha512-yEFYrVhod+hdNyx7g5Bnkkb0G6si8HJurOoOEgC8B/O0uXLHlaey/65KRv6cuWBNhBgHKAROVpc7QyYqE5gFng==";
  };
  "terminal-size@4.0.1" = fetchurl {
    url = "https://registry.npmjs.org/terminal-size/-/terminal-size-4.0.1.tgz";
    hash = "sha512-avMLDQpUI9I5XFrklECw1ZEUPJhqzcwSWsyyI8blhRLT+8N1jLJWLWWYQpB2q2xthq8xDvjZPISVh53T/+CLYQ==";
  };
  "type-fest@5.7.0" = fetchurl {
    url = "https://registry.npmjs.org/type-fest/-/type-fest-5.7.0.tgz";
    hash = "sha512-1URUxUqfHFM1c+zfSPsa3gnkO7Aq21qyH75SIduNYz4SzY964rn1X2vCMQaHSHhktiw+0kPa2iyb6PUpXqB6Vg==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "undici-types@7.24.6" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.24.6.tgz";
    hash = "sha512-WRNW+sJgj5OBN4/0JpHFqtqzhpbnV0GuB+OozA9gCL7a993SmU+1JBZCzLNxYsbMfIeDL+lTsphD5jN5N+n0zg==";
  };
  "widest-line@6.0.0" = fetchurl {
    url = "https://registry.npmjs.org/widest-line/-/widest-line-6.0.0.tgz";
    hash = "sha512-U89AsyEeAsyoF0zVJBkG9zBgekjgjK7yk9sje3F4IQpXBJ10TF6ByLlIfjMhcmHMJgHZI4KHt4rdNfktzxIAMA==";
  };
  "wrap-ansi@9.0.2" = fetchurl {
    url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-9.0.2.tgz";
    hash = "sha512-42AtmgqjV+X1VpdOfyTGOYRi0/zsoLqtXQckTmqTeybT+BDIbM/Guxo7x3pE2vtpr1ok6xRqM9OpBe+Jyoqyww==";
  };
  "ws@7.5.11" = fetchurl {
    url = "https://registry.npmjs.org/ws/-/ws-7.5.11.tgz";
    hash = "sha512-zS54Oen9bITtp7kp2XM3AydrCIq1D+HwJOuH+c+e4LfpL/lotP5osijd+UoMnxwAam1GN8R4KtLAyIrIcBNpiA==";
  };
  "ws@8.21.0" = fetchurl {
    url = "https://registry.npmjs.org/ws/-/ws-8.21.0.tgz";
    hash = "sha512-Vsp28b7DRcimFQvrqu2Wek3z1iYxDCWqHYB8Qsnk/S4RfaCQzPGPyBNuVjJV3cd6UiKtUtp6sNM77gWvzcCH+g==";
  };
  "yoga-layout@3.2.1" = fetchurl {
    url = "https://registry.npmjs.org/yoga-layout/-/yoga-layout-3.2.1.tgz";
    hash = "sha512-0LPOt3AxKqMdFBZA3HBAt/t/8vIKq7VaQYbuA8WxCgung+p9TVyKRYdpvCb80HcdTN2NkbIKbhNwKUfm3tQywQ==";
  };
}